
package employment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmploymentRecordService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8080/EmploymentOffice/EmploymentRecordService?wsdl")
public class EmploymentRecordService
    extends Service
{

    private final static URL EMPLOYMENTRECORDSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYMENTRECORDSERVICE_EXCEPTION;
    private final static QName EMPLOYMENTRECORDSERVICE_QNAME = new QName("http://services/", "EmploymentRecordService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EmploymentOffice/EmploymentRecordService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYMENTRECORDSERVICE_WSDL_LOCATION = url;
        EMPLOYMENTRECORDSERVICE_EXCEPTION = e;
    }

    public EmploymentRecordService() {
        super(__getWsdlLocation(), EMPLOYMENTRECORDSERVICE_QNAME);
    }

    public EmploymentRecordService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYMENTRECORDSERVICE_QNAME, features);
    }

    public EmploymentRecordService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYMENTRECORDSERVICE_QNAME);
    }

    public EmploymentRecordService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYMENTRECORDSERVICE_QNAME, features);
    }

    public EmploymentRecordService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmploymentRecordService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmploymentRecord
     */
    @WebEndpoint(name = "EmploymentRecordPort")
    public EmploymentRecord getEmploymentRecordPort() {
        return super.getPort(new QName("http://services/", "EmploymentRecordPort"), EmploymentRecord.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmploymentRecord
     */
    @WebEndpoint(name = "EmploymentRecordPort")
    public EmploymentRecord getEmploymentRecordPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "EmploymentRecordPort"), EmploymentRecord.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYMENTRECORDSERVICE_EXCEPTION!= null) {
            throw EMPLOYMENTRECORDSERVICE_EXCEPTION;
        }
        return EMPLOYMENTRECORDSERVICE_WSDL_LOCATION;
    }

}
