
package employment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmploymentRecord", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmploymentRecord {


    /**
     * 
     * @param personname
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmploymentRecord", targetNamespace = "http://services/", className = "employment.GetEmploymentRecord")
    @ResponseWrapper(localName = "getEmploymentRecordResponse", targetNamespace = "http://services/", className = "employment.GetEmploymentRecordResponse")
    @Action(input = "http://services/EmploymentRecord/getEmploymentRecordRequest", output = "http://services/EmploymentRecord/getEmploymentRecordResponse")
    public String getEmploymentRecord(
        @WebParam(name = "personname", targetNamespace = "")
        String personname);

}
