
package jobdescription;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JobDescriptionService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8080/JobServiceCompany/JobDescriptionService?wsdl")
public class JobDescriptionService
    extends Service
{

    private final static URL JOBDESCRIPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException JOBDESCRIPTIONSERVICE_EXCEPTION;
    private final static QName JOBDESCRIPTIONSERVICE_QNAME = new QName("http://services/", "JobDescriptionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JobServiceCompany/JobDescriptionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOBDESCRIPTIONSERVICE_WSDL_LOCATION = url;
        JOBDESCRIPTIONSERVICE_EXCEPTION = e;
    }

    public JobDescriptionService() {
        super(__getWsdlLocation(), JOBDESCRIPTIONSERVICE_QNAME);
    }

    public JobDescriptionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOBDESCRIPTIONSERVICE_QNAME, features);
    }

    public JobDescriptionService(URL wsdlLocation) {
        super(wsdlLocation, JOBDESCRIPTIONSERVICE_QNAME);
    }

    public JobDescriptionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOBDESCRIPTIONSERVICE_QNAME, features);
    }

    public JobDescriptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobDescriptionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JobDescription
     */
    @WebEndpoint(name = "JobDescriptionPort")
    public JobDescription getJobDescriptionPort() {
        return super.getPort(new QName("http://services/", "JobDescriptionPort"), JobDescription.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobDescription
     */
    @WebEndpoint(name = "JobDescriptionPort")
    public JobDescription getJobDescriptionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "JobDescriptionPort"), JobDescription.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOBDESCRIPTIONSERVICE_EXCEPTION!= null) {
            throw JOBDESCRIPTIONSERVICE_EXCEPTION;
        }
        return JOBDESCRIPTIONSERVICE_WSDL_LOCATION;
    }

}
